name: pomoduo
description: Shared pomodoro timer for teams


publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
    sdk: ">=2.16.2 <3.0.0"


dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    google_fonts: ^2.3.2
    font_awesome: ^5.10.1

    custom_radio_grouped_button: ^2.1.2
    percent_indicator: ^4.0.1
    step_progress_indicator: ^1.0.2

    firebase_core: ^1.6.0
    cloud_firestore: ^2.5.1
    firebase_auth: ^3.3.18
    google_sign_in: ^5.3.1

    intl: ^0.17.0
    http: ^0.13.4

    provider: ^6.0.2


dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0


flutter:
    uses-material-design: true
    fonts:
        - family: Quicksand
          fonts:
              - asset: fonts/Quicksand-Medium.ttf
                weight: 400
              - asset: fonts/Quicksand-Bold.ttf
                weight: 700
